# Fly.io configuration for Voice AI Agents
app = "voice-ai-agents-openai-telnyx"
primary_region = "iad"

# Runtime configuration
kill_signal = "SIGTERM"
kill_timeout = 30

# Build configuration
[build]
  dockerfile = "Dockerfile"

# Environment variables
[env]
  PORT = "8000"
  PYTHONPATH = "/app"

# HTTP service configuration
[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  
  [http_service.concurrency]
    type = "requests"
    soft_limit = 50
    hard_limit = 100

  # Health checks
  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

# VM configuration
[[vm]]
  size = "shared-cpu-2x"
  memory = "1gb"

# Deploy configuration
[deploy]
  strategy = "rolling"
  max_unavailable = 1
  wait_timeout = "10m"
